import Foundation

enum AppLanguage: String, CaseIterable, Identifiable, Codable {
    case zhHans
    case zhHant
    case en
    case ko
    case ja
    case es
    case fr
    case de
    case it
    case ru

    var id: String { rawValue }

    var displayName: String {
        switch self {
        case .zhHans: "简体中文"
        case .zhHant: "繁體中文"
        case .en: "English"
        case .ko: "한국어"
        case .ja: "日本語"
        case .es: "Español"
        case .fr: "Français"
        case .de: "Deutsch"
        case .it: "Italiano"
        case .ru: "Русский"
        }
    }

    var localeIdentifier: String {
        switch self {
        case .zhHans: "zh_CN"
        case .zhHant: "zh_TW"
        case .en: "en_US"
        case .ko: "ko_KR"
        case .ja: "ja_JP"
        case .es: "es_ES"
        case .fr: "fr_FR"
        case .de: "de_DE"
        case .it: "it_IT"
        case .ru: "ru_RU"
        }
    }

    var locale: Locale { Locale(identifier: localeIdentifier) }

    var apiCode: String {
        switch self {
        case .zhHans: "zh-Hans"
        case .zhHant: "zh-Hant"
        case .en: "en"
        case .ko: "ko"
        case .ja: "ja"
        case .es: "es"
        case .fr: "fr"
        case .de: "de"
        case .it: "it"
        case .ru: "ru"
        }
    }

    static func storedValue() -> AppLanguage {
        let value = UserDefaults.standard.string(forKey: "secflow.appLanguage") ?? AppLanguage.zhHans.rawValue
        return AppLanguage(rawValue: value) ?? .zhHans
    }
}

enum L10nKey: String {
    case appName
    case appVersion
    case navOverview
    case navAssistant
    case navKnowledgeGraph
    case navQueryResults
    case navInformation
    case navReports
    case settings
    case settingsSubtitle
    case languageTitle
    case languageSubtitle
    case interfaceLanguage
    case languageHint
    case llmAccess
    case llmAccessSubtitle
    case selectProvider
    case selectModel
    case customModel
    case customModelPlaceholder
    case syncModels
    case syncing
    case apiAndKey
    case apiKeyLocalOnly
    case apiEndpoint
    case apiKey
    case showApiKey
    case hideApiKey
    case howToGetApiKey
    case testing
    case testConnection
    case saving
    case saveAndEnable
    case connected
    case disconnected
    case disconnect
    case savedModel
    case localConfig
    case providerModelsSynced
    case builtinModelsShown
    case defaultModelHint
    case justNow
    case lastVerifiedAt
    case chooseModelAndKey
    case refreshData
    case signOut
    case localServiceStarting
    case localDataConnected
    case setupChecking
    case setupCheckingSubtitle
    case setupFailed
    case retry
    case dateRangeHelp
    case previousMonth
    case nextMonth
    case selectMonth
    case selectYear
}

func localized(_ key: L10nKey, language: AppLanguage, _ arguments: CVarArg...) -> String {
    if key == .appVersion, arguments.isEmpty {
        return AppBrand.versionLabel
    }
    let fallbackLanguage: AppLanguage = (language == .zhHans || language == .zhHant) ? .zhHans : .en
    let template = AppLocalization.table[language]?[key]
        ?? AppLocalization.table[fallbackLanguage]?[key]
        ?? AppLocalization.table[.zhHans]?[key]
        ?? key.rawValue
    if arguments.isEmpty {
        return template
    }
    return String(format: template, locale: language.locale, arguments: arguments)
}

func localizedUI(_ text: String, language: AppLanguage, _ arguments: CVarArg...) -> String {
    localizedUI(text, language: language, arguments: arguments)
}

func localizedUI(_ text: String, language: AppLanguage, arguments: [CVarArg]) -> String {
    let fallbackLanguage: AppLanguage = (language == .zhHans || language == .zhHant) ? .zhHans : .en
    let template = AppLocalization.uiTable[language]?[text]
        ?? AppLocalization.uiTable[fallbackLanguage]?[text]
        ?? AppLocalization.uiTable[.zhHans]?[text]
        ?? text
    if arguments.isEmpty {
        return template
    }
    return String(format: template, locale: language.locale, arguments: arguments)
}

enum AppLocalization {
    static let uiTable: [AppLanguage: [String: String]] = [
        .zhHans: [:],
        .en: [
            "安全提醒": "Security alerts",
            "暂无新的安全提醒": "No new security alerts",
            "漏洞总数": "Total vulnerabilities",
            "严重漏洞": "Critical vulnerabilities",
            "高危漏洞": "High vulnerabilities",
            "中危漏洞": "Medium vulnerabilities",
            "低危漏洞": "Low vulnerabilities",
            "按漏洞编号聚合去重": "Deduplicated by vulnerability ID",
            "等待首次批计算": "Waiting for the first batch update",
            "最近更新：%@": "Last updated: %@",
            "累计漏洞风险态势，后台持续增量更新": "Cumulative vulnerability risk posture, updated continuously in the background",
            "%@ 至 %@ 发布的漏洞风险态势": "Vulnerability risk posture published from %@ to %@",
            "本地全量目录已就绪，共 %d 条": "Local full catalog is ready, %d items",
            "正在构建本地全量目录 %d%%": "Building local full catalog %d%%",
            "正在准备本地全量目录": "Preparing local full catalog",
            "占全部漏洞 0%": "0% of all vulnerabilities",
            "占全部漏洞 %d%%": "%d%% of all vulnerabilities",
            "全部时间": "All time",
            "最近 7 天": "Last 7 days",
            "最近 30 天": "Last 30 days",
            "最近 90 天": "Last 90 days",
            "今年": "This year",
            "自定义范围": "Custom range",
            "最新漏洞动态": "Latest vulnerability activity",
            "最近一次批计算返回的漏洞记录": "Vulnerability records from the latest batch update",
            "查看查询日志": "View query logs",
            "暂无漏洞数据": "No vulnerability data",
            "批计算完成后将在这里显示最新漏洞。": "Latest vulnerabilities will appear here after the batch update completes.",
            "未提供漏洞标题": "No vulnerability title provided",
            "发布于 %@": "Published %@",
            "风险快速统计": "Quick risk statistics",
            "漏洞情报风险图表": "Vulnerability intelligence risk charts",
            "按严重等级展示环形图与柱状图": "Ring and bar charts by severity",
            "风险柱状图": "Risk bar chart",
            "按漏洞数量排序": "Sorted by vulnerability count",
            "数据来自本地批计算快照，并随时间范围筛选实时更新": "Data comes from the local batch snapshot and updates with the selected time range",
            "严重": "Critical",
            "高危": "High",
            "中危": "Medium",
            "低危": "Low",
            "重点风险": "Priority risks",
            "暂无需要优先关注的漏洞": "No vulnerabilities currently require priority attention",
            "时间未知": "Unknown time",
            "未知": "Unknown",
            "安全总览已更新累计数据": "Overview cumulative data updated",
            "安全总览已按时间范围更新": "Overview updated for the selected time range",
            "安全总览已切换到所选发布日期范围": "Overview switched to the selected publication date range",
            "本机数据服务已连接": "Local data service connected",
            "服务地址无效，请在设置中填写完整的 http 或 https 地址。": "Invalid service address. Enter a complete http or https URL in Settings.",
            "服务返回了无法识别的响应。": "The service returned an unrecognized response.",
            "本地数据解析失败：%@": "Local data parsing failed: %@",
            "应用内本地服务缺失，请重新安装 SecFlow。": "The embedded local service is missing. Please reinstall SecFlow.",
            "本地服务启动失败：%@": "Failed to start the local service: %@",
            "开发服务 %@ 无法连接。": "Development service %@ cannot be reached.",
            "进程已退出，请查看 %@。": "The process exited. Check %@.",
            "等待本地服务就绪超时，请查看 %@。": "Timed out waiting for the local service. Check %@.",
            "模型配置已启用。": "Model configuration is enabled.",
            "模型配置已保存，尚未启用。": "Model configuration saved but not enabled.",
            "未配置可用模型。": "No available model is configured.",
            "模型接口返回格式不符合 OpenAI Chat Completions。": "The model API response does not match OpenAI Chat Completions.",
            "当前模型未返回可用结果。": "The current model did not return a usable result.",
            "模型接口调用成功。": "Model API call succeeded.",
            "填入 API Key 后，可从厂商模型接口同步真实模型列表。": "Enter an API Key to sync the real model list from the provider API.",
            "API 地址需要包含 http:// 或 https://，当前显示内置推荐模型。": "The API endpoint must include http:// or https://. Built-in recommended models are shown for now.",
            "厂商接口未返回可用模型，已使用内置推荐模型。": "The provider API returned no usable models. Built-in recommended models are used.",
            "已从厂商模型接口同步模型列表。": "Model list synced from the provider API.",
            "固定接口可访问。": "Fixed API is reachable.",
            "查询完成": "Query completed",
            "查询失败": "Query failed",
            "部分完成": "Partially completed",
            "等待查询": "Waiting for query",
            "模型接口请求失败：%@": "Model API request failed: %@",
            "厂商模型列表同步失败，已使用内置推荐模型：%@": "Provider model sync failed; built-in recommended models are used: %@",
            "%@ 的接口地址需要包含 http:// 或 https://。": "%@ endpoint must include http:// or https://.",
            "大模型配置已保存并启用": "AI model configuration saved and enabled",
            "大模型连接已断开": "AI model connection disconnected",
            "连接测试已完成": "Connection test completed",
            "个人资料": "Profile",
            "管理头像、联系方式和岗位资料，资料仅保存在本机。": "Manage your avatar, contact details, and role profile. Data stays on this Mac.",
            "保存资料": "Save profile",
            "上传头像": "Upload avatar",
            "移除": "Remove",
            "支持 JPG、PNG、WebP，文件大小不超过 2MB": "Supports JPG, PNG, and WebP up to 2 MB",
            "姓名": "Name",
            "工号": "Employee ID",
            "所属部门": "Department",
            "职位": "Role",
            "邮箱": "Email",
            "手机号": "Phone",
            "个人简介": "Bio",
            "%d / 200 字": "%d / 200 chars",
            "姓名不能为空": "Name cannot be empty",
            "邮箱不能为空": "Email cannot be empty",
            "个人资料已保存": "Profile saved",
            "头像上传失败：%@": "Avatar upload failed: %@",
            "头像已上传并保存在本机": "Avatar uploaded and stored locally",
            "头像已移除": "Avatar removed",
            "仅支持 JPG、PNG 或 WebP 图片": "Only JPG, PNG, or WebP images are supported",
            "头像文件不能超过 2MB": "Avatar file must be no larger than 2 MB",
            "无法读取图片内容": "Cannot read image content",
            "请选择一个有效的图片文件": "Choose a valid image file",

            "智能问答": "Assistant",
            "新对话": "New chat",
            "新建对话": "Start new chat",
            "添加项目清单、代码附件或完整项目目录": "Add project manifests, code files, or a full project folder",
            "输入安全问题，获取智能分析…": "Ask a security question for AI analysis…",
            "停止生成": "Stop",
            "发送": "Send",
            "松开即可添加项目或附件": "Drop to add the project or files",
            "支持拖入 Python、Go、C/C++、Rust、Solidity、Java 项目；会自动忽略构建产物目录": "Drop Python, Go, C/C++, Rust, Solidity, or Java projects. Build output folders are ignored automatically.",
            "请输入包含文字或数字的具体安全问题": "Enter a specific security question containing letters or numbers",
            "本地安全分析暂时不可用。": "Local security analysis is temporarily unavailable.",
            "附件读取失败：%@": "Failed to read attachment: %@",
            "请拖入项目清单或代码文件": "Drop a project manifest or code file",
            "无法识别拖入的文件": "Cannot identify the dropped file",
            "最多支持添加 %d 个项目文件": "Up to %d project files can be added",
            "项目文件内容过大，已超过本次分析的上传上限": "Project files are too large for this analysis upload limit",
            "未找到可分析的项目清单或代码文件": "No analyzable project manifests or code files found",
            "请分析附件 %@": "Please analyze attachment %@",
            "请分析 %d 个附件：%@": "Please analyze %d attachments: %@",
            "移除附件": "Remove attachment",
            "漏洞": "Vulnerability",
            "%@ 漏洞分析报告": "%@ vulnerability analysis report",
            "漏洞描述": "Vulnerability description",
            "风险待核验": "Risk pending verification",
            "根据知识图谱分析，您的系统中以下组件可能受到影响：": "Based on knowledge graph analysis, the following components may be affected:",
            "组件版本范围": "Component version range",
            "涉及版本": "Affected versions",
            "修复版本": "Fixed versions",
            "修复方案": "Remediation",
            "缓释措施": "Mitigation",
            "参考链接": "References",
            "代码片段": "Code snippet",
            "修复代码片段": "Fixed code snippet",
            "受影响版本待核验": "Affected versions pending verification",
            "影响 %@": "Affects %@",
            "有帮助": "Helpful",
            "需改进": "Needs improvement",
            "已复制": "Copied",
            "复制": "Copy",
            "分享": "Share",
            "正在分析 · %d 秒": "Analyzing · %d sec",
            "模型处理中 · %d 秒": "Model processing · %d sec",
            "已停止生成": "Generation stopped",
            "依赖关系图表": "Dependency relationship charts",
            "依赖桑基图": "Dependency Sankey",
            "构建文件 / 代码文件 → 依赖 → CVE → 修复版本": "Build file / code file → dependency → CVE → fixed version",
            "风险等级环形图": "Severity ring chart",
            "按严重等级统计漏洞数量": "Vulnerability count by severity",
            "依赖风险柱状图": "Dependency risk bar chart",
            "命中漏洞最多的依赖": "Dependencies with the most vulnerability hits",
            "依赖影响有向无环图": "Dependency impact DAG",
            "按层级展示依赖、漏洞与修复路径": "Layered dependency, vulnerability, and remediation path",
            "命中": "Hits",

            "知识图谱": "Knowledge Graph",
            "输入 CVE 编号，生成漏洞知识图谱": "Enter a CVE ID to generate a vulnerability knowledge graph",
            "查询图谱": "Query graph",
            "暂无图谱": "No graph yet",
            "拖动画布移动 · 双指捏合或按钮缩放": "Drag to pan · pinch or use buttons to zoom",
            "缩小": "Zoom out",
            "放大": "Zoom in",
            "居中": "Center",
            "组件": "Component",
            "弱点": "Weakness",
            "修复": "Fix",
            "公告": "Advisory",
            "关联公告": "Related advisory",
            "暂无更多详情": "No more details",
            "关联实体": "Related entities",
            "选择图节点": "Select a graph node",
            "严重等级": "Severity",
            "名称": "Name",
            "描述": "Description",
            "生态": "Ecosystem",
            "影响范围": "Affected range",
            "来源链接": "Reference links",
            "关联编号": "Related IDs",
            "弱点类型": "Weakness types",
            "发布时间": "Published at",
            "更新时间": "Updated at",
            "修复方式": "Fix guidance",

            "查询结果": "Query logs",
            "查看历史查询记录和详情": "View historical query logs and details",
            "仅保存和展示 API 查询日志，不保存漏洞明细数据": "Only API query logs are stored and shown. Vulnerability details are not persisted.",
            "刷新": "Refresh",
            "%d 条日志": "%d logs",
            "搜索查询内容、状态或执行节点": "Search query, status, or execution node",
            "查询内容": "Query",
            "状态": "Status",
            "返回数": "Returned",
            "图谱": "Graph",
            "时间": "Time",
            "暂无查询日志": "No query logs",
            "暂无查询记录": "No query logs",
            "通过知识图谱或智能问答触发漏洞查询后，这里只记录查询日志。": "After a vulnerability query is triggered from Knowledge Graph or Assistant, only the query log is recorded here.",
            "完成": "Completed",
            "警告": "Warning",
            "失败": "Failed",
            "运行中": "Running",
            "节点": "Node",
            "%d 个执行节点 · 后端固定情报接口": "%d execution nodes · backend fixed intelligence APIs",
            "查看详情": "View details",
            "收起详情": "Collapse details",
            "查询详情": "Query details",
            "查询日志详情": "Query log details",
            "查询摘要": "Query summary",
            "查询状态": "Query status",
            "执行时间": "Execution time",
            "数据策略": "Data policy",
            "仅保留查询日志，不保存漏洞明细": "Only query logs are kept. Vulnerability details are not stored.",
            "统计概览": "Statistics overview",
            "返回 %d 条 · 图谱 %d 节点 / %d 关系 · 本地写入 %d": "%d returned · graph %d nodes / %d edges · local writes %d",
            "图谱概览": "Graph overview",
            "暂无图谱节点": "No graph nodes",
            "图谱节点": "Graph nodes",
            "图谱关系": "Graph edges",
            "执行日志": "Execution log",
            "暂无执行日志": "No execution log",
            "%@ · 共 %d 个执行节点": "%@ · %d execution nodes",
            "%@ 等 %d 个节点": "%@ and %d nodes",
            "%d 个节点": "%d nodes",
            "%@ · %@ / %d 条关系": "%@ · %@ / %d edges",
            "返回记录": "Returned records",
            "关联节点": "Related nodes",
            "关联关系": "Relationships",
            "本地写入": "Local writes",
            "暂无执行记录": "No execution records",
            "关闭": "Close",
            "识别问题意图": "Classify intent",
            "加载长期记忆": "Load memory context",
            "检索漏洞知识": "Retrieve vulnerability knowledge",
            "实时补充记录": "Fetch live vulnerability records",
            "查询漏洞接口": "Query vulnerability APIs",
            "静态代码路径分析": "Static code path analysis",
            "生成知识图谱": "Generate knowledge graph",
            "接口查询准备": "Prepare API query",
            "查询外部接口": "Query external APIs",
            "接口结果暂存": "Stage API results",
            "调用安全模型": "Call security model",
            "整理漏洞卡片": "Prepare vulnerability card",
            "生成回答": "Generate answer",
            "生成分析报告": "Generate analysis report",
            "保存长期记忆": "Save memory",
            "准备查询环境": "Prepare query environment",
            "拉取情报记录": "Fetch intelligence records",
            "规范化与去重": "Normalize and deduplicate",
            "跳过本地写入": "Skip local write",
            "汇总查询结果": "Compose query result",
            "别名": "Alias",
            "影响组件": "Affects component",

            "报告中心": "Reports",
            "上传项目清单与代码后，系统会分别展示依赖漏洞，以及 AST/CFG/DFG 路径中的具体漏洞位置和修复代码。": "After uploading project manifests and code, the system separates dependency vulnerabilities from code findings with exact AST/CFG/DFG paths and fixed code.",
            "删除选中的 %d 份报告？": "Delete %d selected reports?",
            "取消": "Cancel",
            "删除": "Delete",
            "报告文件和对应记录会被永久删除，此操作无法撤销。": "Report files and records will be permanently deleted. This action cannot be undone.",
            "分析报告": "Analysis reports",
            "取消全选": "Deselect all",
            "全选": "Select all",
            "删除选中的报告": "Delete selected reports",
            "选择": "Select",
            "暂无分析报告": "No analysis reports",
            "下载报告": "Download report",
            "下载 Markdown": "Download Markdown",
            "下载 HTML": "Download HTML",
            "下载 PDF": "Download PDF",
            "报告 Markdown 已复制": "Report Markdown copied",
            "复制 Markdown": "Copy Markdown",
            "依赖漏洞 %d": "Dependency vulnerabilities %d",
            "代码漏洞 %d": "Code findings %d",
            "请选择报告": "Select a report",
            "下载分析报告": "Download analysis report",
            "下载%@分析报告": "Download %@ analysis report",
            "点击查看详细内容": "Click to view details",
            "报告概览": "Report overview",
            "%d 项": "%d items",
            "代码": "Code",
            "复制代码": "Copy code",
            "报告已保存到 %@": "Report saved to %@",
            "已删除 %d 份报告": "%d reports deleted",
            "API 返回 %d 条漏洞记录": "API returned %d vulnerability records",

            "AI 驱动的安全知识库智能体\n漏洞分析 · 威胁情报 · 知识图谱": "AI-powered security knowledge agent\nVulnerability analysis · Threat intelligence · Knowledge graph",
            "创建您的安全智脑账户\n开启智能安全分析之旅": "Create your SecFlow account\nStart intelligent security analysis",
            "智能问答，秒级响应安全咨询": "Assistant answers security questions in seconds",
            "实时漏洞查询，多源接口关联": "Real-time vulnerability queries with multi-source correlation",
            "知识图谱关联漏洞与组件": "Knowledge graph links vulnerabilities and components",
            "填写基本信息": "Enter basic information",
            "验证邮箱地址": "Verify email address",
            "设置安全偏好": "Set security preferences",
            "欢迎回来": "Welcome back",
            "登录您的安全智脑账户": "Sign in to your SecFlow account",
            "邮箱地址": "Email address",
            "请输入邮箱地址": "Enter email address",
            "密码": "Password",
            "请输入密码": "Enter password",
            "登 录": "Sign in",
            "或": "or",
            "使用本机账户进入": "Continue with this Mac account",
            "还没有账户？": "No account yet?",
            "立即注册": "Register now",
            "创建账户": "Create account",
            "加入安全智脑，提升安全分析效率": "Join SecFlow and improve security analysis efficiency",
            "姓": "Family name",
            "名": "Given name",
            "请输入": "Enter",
            "工作邮箱": "Work email",
            "设置密码": "Set password",
            "至少8位，包含字母和数字": "At least 8 characters with letters and numbers",
            "确认密码": "Confirm password",
            "请再次输入密码": "Enter password again",
            "所属组织（选填）": "Organization (optional)",
            "公司或团队名称": "Company or team name",
            "角色": "Role",
            "安全分析师": "Security analyst",
            "安全工程师": "Security engineer",
            "安全管理员": "Security administrator",
            "其他": "Other",
            "我同意服务条款和隐私政策": "I agree to the Terms of Service and Privacy Policy",

            "首次配置": "First-time setup",
            "密钥仅加密保存在这台 Mac": "The key is encrypted and stored only on this Mac",
            "选择模型厂商": "Choose provider",
            "选择模型": "Choose model",
            "自定义模型 ID…": "Custom model ID…",
            "填写连接信息": "Enter connection details",
            "验证并完成": "Verify and finish",
            "配置 AI 模型": "Configure AI model",
            "完成连接后即可使用智能问答和报告分析": "After connecting, Assistant and report analysis are available",
            "第 %d / 4 步": "Step %d / 4",
            "请选择你已经开通 API 服务的厂商": "Choose the provider whose API service you have enabled",
            "选择具体模型": "Choose model",
            "模型列表遵循 %@ 的接口规范": "The model list follows %@ API conventions",
            "模型": "Model",
            "输入厂商模型 ID": "Enter provider model ID",
            "API Key 初始为空，需要使用者自行填写": "API Key starts empty and must be entered by the user",
            "API 地址": "API endpoint",
            "前往 %@ 获取 API Key": "Go to %@ to get an API Key",
            "验证连接": "Verify connection",
            "测试成功后才会把配置写入本机加密存储": "Configuration is written to local encrypted storage only after a successful test",
            "厂商": "Provider",
            "已填写，不显示明文": "Entered, plaintext hidden",
            "正在测试": "Testing",
            "上一步": "Back",
            "下一步": "Next",
            "正在保存": "Saving",
            "保存并进入": "Save and enter",
        ],
        .ja: [
            "安全提醒": "セキュリティアラート",
            "暂无新的安全提醒": "新しいセキュリティアラートはありません",
            "漏洞总数": "脆弱性総数",
            "严重漏洞": "重大な脆弱性",
            "高危漏洞": "高リスク脆弱性",
            "中危漏洞": "中リスク脆弱性",
            "低危漏洞": "低リスク脆弱性",
            "按漏洞编号聚合去重": "脆弱性 ID で重複排除",
            "等待首次批计算": "初回バッチ更新待ち",
            "最近更新：%@": "最終更新：%@",
            "累计漏洞风险态势，后台持续增量更新": "累積脆弱性リスク状況。バックグラウンドで継続更新",
            "%@ 至 %@ 发布的漏洞风险态势": "%@ から %@ に公開された脆弱性リスク状況",
            "本地全量目录已就绪，共 %d 条": "ローカル全量カタログ準備完了、計 %d 件",
            "正在构建本地全量目录 %d%%": "ローカル全量カタログ構築中 %d%%",
            "正在准备本地全量目录": "ローカル全量カタログを準備中",
            "占全部漏洞 0%": "全脆弱性の 0%",
            "占全部漏洞 %d%%": "全脆弱性の %d%%",
            "全部时间": "全期間",
            "最近 7 天": "過去 7 日",
            "最近 30 天": "過去 30 日",
            "最近 90 天": "過去 90 日",
            "今年": "今年",
            "自定义范围": "カスタム範囲",
            "最新漏洞动态": "最新脆弱性動向",
            "最近一次批计算返回的漏洞记录": "直近のバッチ更新で返された脆弱性レコード",
            "查看查询日志": "照会ログを見る",
            "暂无漏洞数据": "脆弱性データはありません",
            "批计算完成后将在这里显示最新漏洞。": "バッチ更新完了後、ここに最新脆弱性が表示されます。",
            "未提供漏洞标题": "脆弱性タイトル未提供",
            "发布于 %@": "公開日 %@",
            "风险快速统计": "リスク簡易統計",
            "漏洞情报风险图表": "脆弱性インテリジェンスリスクチャート",
            "按严重等级展示环形图与柱状图": "深刻度別のリング図と棒グラフ",
            "风险柱状图": "リスク棒グラフ",
            "按漏洞数量排序": "脆弱性件数順",
            "数据来自本地批计算快照，并随时间范围筛选实时更新": "データはローカルバッチスナップショットに基づき、選択期間に応じて更新されます",
            "严重": "重大",
            "高危": "高",
            "中危": "中",
            "低危": "低",
            "重点风险": "重点リスク",
            "暂无需要优先关注的漏洞": "優先対応が必要な脆弱性はありません",
            "时间未知": "時刻不明",
            "未知": "不明",
            "安全总览已更新累计数据": "概要の累積データを更新しました",
            "安全总览已按时间范围更新": "概要を選択期間で更新しました",
            "安全总览已切换到所选发布日期范围": "概要を選択した公開日範囲に切り替えました",
            "本机数据服务已连接": "ローカルデータサービス接続済み",
            "服务地址无效，请在设置中填写完整的 http 或 https 地址。": "サービスアドレスが無効です。設定で完全な http または https URL を入力してください。",
            "服务返回了无法识别的响应。": "サービスが認識できないレスポンスを返しました。",
            "本地数据解析失败：%@": "ローカルデータの解析に失敗しました：%@",
            "应用内本地服务缺失，请重新安装 SecFlow。": "アプリ内のローカルサービスが見つかりません。SecFlow を再インストールしてください。",
            "本地服务启动失败：%@": "ローカルサービスの起動に失敗しました：%@",
            "开发服务 %@ 无法连接。": "開発サービス %@ に接続できません。",
            "进程已退出，请查看 %@。": "プロセスが終了しました。%@ を確認してください。",
            "等待本地服务就绪超时，请查看 %@。": "ローカルサービスの起動待ちがタイムアウトしました。%@ を確認してください。",
            "模型配置已启用。": "モデル設定は有効です。",
            "模型配置已保存，尚未启用。": "モデル設定は保存されましたが、まだ有効化されていません。",
            "未配置可用模型。": "利用可能なモデルが設定されていません。",
            "模型接口返回格式不符合 OpenAI Chat Completions。": "モデル API のレスポンス形式が OpenAI Chat Completions と一致しません。",
            "当前模型未返回可用结果。": "現在のモデルは利用可能な結果を返しませんでした。",
            "模型接口调用成功。": "モデル API の呼び出しに成功しました。",
            "填入 API Key 后，可从厂商模型接口同步真实模型列表。": "API Key を入力すると、プロバイダ API から実際のモデル一覧を同期できます。",
            "API 地址需要包含 http:// 或 https://，当前显示内置推荐模型。": "API アドレスには http:// または https:// が必要です。現在は内蔵の推奨モデルを表示しています。",
            "厂商接口未返回可用模型，已使用内置推荐模型。": "プロバイダ API が利用可能なモデルを返さなかったため、内蔵の推奨モデルを使用しています。",
            "已从厂商模型接口同步模型列表。": "プロバイダ API からモデル一覧を同期しました。",
            "固定接口可访问。": "固定 API にアクセスできます。",
            "查询完成": "照会完了",
            "查询失败": "照会失敗",
            "部分完成": "一部完了",
            "等待查询": "照会待ち",
            "模型接口请求失败：%@": "モデル API リクエストに失敗しました：%@",
            "厂商模型列表同步失败，已使用内置推荐模型：%@": "プロバイダモデル一覧の同期に失敗したため、内蔵の推奨モデルを使用しています：%@",
            "%@ 的接口地址需要包含 http:// 或 https://。": "%@ のエンドポイントには http:// または https:// が必要です。",
            "大模型配置已保存并启用": "AI モデル設定を保存して有効化しました",
            "大模型连接已断开": "AI モデル接続を切断しました",
            "连接测试已完成": "接続テストが完了しました",
            "个人资料": "プロフィール",
            "管理头像、联系方式和岗位资料，资料仅保存在本机。": "アバター、連絡先、職務情報を管理します。データはこの Mac にのみ保存されます。",
            "保存资料": "プロフィールを保存",
            "上传头像": "アバターをアップロード",
            "移除": "削除",
            "支持 JPG、PNG、WebP，文件大小不超过 2MB": "JPG、PNG、WebP に対応、最大 2 MB",
            "姓名": "氏名",
            "工号": "社員 ID",
            "所属部门": "所属部門",
            "职位": "役職",
            "邮箱": "メール",
            "手机号": "電話番号",
            "个人简介": "自己紹介",
            "%d / 200 字": "%d / 200 文字",
            "姓名不能为空": "氏名は空にできません",
            "邮箱不能为空": "メールは空にできません",
            "个人资料已保存": "プロフィールを保存しました",
            "头像上传失败：%@": "アバターのアップロードに失敗しました：%@",
            "头像已上传并保存在本机": "アバターをアップロードしローカルに保存しました",
            "头像已移除": "アバターを削除しました",
            "仅支持 JPG、PNG 或 WebP 图片": "JPG、PNG、WebP 画像のみ対応しています",
            "头像文件不能超过 2MB": "アバター画像は 2 MB 以下にしてください",
            "无法读取图片内容": "画像内容を読み取れません",
            "请选择一个有效的图片文件": "有効な画像ファイルを選択してください",
            "智能问答": "AI チャット",
            "新对话": "新規チャット",
            "新建对话": "新しいチャットを開始",
            "添加项目清单、代码附件或完整项目目录": "プロジェクトマニフェスト、コード添付、またはプロジェクトフォルダを追加",
            "输入安全问题，获取智能分析…": "セキュリティ質問を入力して AI 分析…",
            "停止生成": "停止",
            "发送": "送信",
            "松开即可添加项目或附件": "ドロップしてプロジェクトまたは添付を追加",
            "支持拖入 Python、Go、C/C++、Rust、Solidity、Java 项目；会自动忽略构建产物目录": "Python、Go、C/C++、Rust、Solidity、Java プロジェクトをドロップできます。ビルド成果物フォルダは自動的に無視されます。",
            "请输入包含文字或数字的具体安全问题": "文字または数字を含む具体的なセキュリティ質問を入力してください",
            "本地安全分析暂时不可用。": "ローカルセキュリティ分析は一時的に利用できません。",
            "附件读取失败：%@": "添付読み取り失敗：%@",
            "请拖入项目清单或代码文件": "プロジェクトマニフェストまたはコードファイルをドロップしてください",
            "无法识别拖入的文件": "ドロップされたファイルを識別できません",
            "最多支持添加 %d 个项目文件": "最大 %d 個のプロジェクトファイルを追加できます",
            "项目文件内容过大，已超过本次分析的上传上限": "プロジェクトファイルが大きすぎ、今回のアップロード上限を超えました",
            "未找到可分析的项目清单或代码文件": "分析可能なプロジェクトマニフェストまたはコードファイルが見つかりません",
            "请分析附件 %@": "添付 %@ を分析してください",
            "请分析 %d 个附件：%@": "%d 個の添付を分析してください：%@",
            "移除附件": "添付を削除",
            "漏洞": "脆弱性",
            "%@ 漏洞分析报告": "%@ 脆弱性分析レポート",
            "漏洞描述": "脆弱性説明",
            "风险待核验": "リスク確認待ち",
            "根据知识图谱分析，您的系统中以下组件可能受到影响：": "ナレッジグラフ分析に基づき、以下のコンポーネントが影響を受ける可能性があります：",
            "组件版本范围": "コンポーネントバージョン範囲",
            "涉及版本": "影響バージョン",
            "修复版本": "修正バージョン",
            "修复方案": "修正方法",
            "缓释措施": "緩和策",
            "参考链接": "参考リンク",
            "代码片段": "コード片",
            "修复代码片段": "修正コード片",
            "受影响版本待核验": "影響バージョン確認待ち",
            "影响 %@": "%@ に影響",
            "有帮助": "役に立つ",
            "需改进": "改善が必要",
            "已复制": "コピー済み",
            "复制": "コピー",
            "分享": "共有",
            "正在分析 · %d 秒": "分析中 · %d 秒",
            "模型处理中 · %d 秒": "モデル処理中 · %d 秒",
            "已停止生成": "生成を停止しました",
            "依赖关系图表": "依存関係チャート",
            "依赖桑基图": "依存関係サンキー図",
            "构建文件 / 代码文件 → 依赖 → CVE → 修复版本": "ビルドファイル / コードファイル → 依存関係 → CVE → 修正バージョン",
            "风险等级环形图": "深刻度リングチャート",
            "按严重等级统计漏洞数量": "深刻度別の脆弱性件数",
            "依赖风险柱状图": "依存関係リスク棒グラフ",
            "命中漏洞最多的依赖": "脆弱性ヒット数が多い依存関係",
            "依赖影响有向无环图": "依存関係影響 DAG",
            "按层级展示依赖、漏洞与修复路径": "依存関係・脆弱性・修正パスを階層表示",
            "命中": "ヒット",
            "知识图谱": "ナレッジグラフ",
            "输入 CVE 编号，生成漏洞知识图谱": "CVE ID を入力して脆弱性ナレッジグラフを生成",
            "查询图谱": "グラフ照会",
            "暂无图谱": "グラフはありません",
            "拖动画布移动 · 双指捏合或按钮缩放": "ドラッグで移動 · ピンチまたはボタンでズーム",
            "缩小": "縮小",
            "放大": "拡大",
            "居中": "中央に戻す",
            "组件": "コンポーネント",
            "弱点": "弱点",
            "修复": "修正",
            "公告": "アドバイザリ",
            "关联公告": "関連アドバイザリ",
            "暂无更多详情": "追加詳細はありません",
            "关联实体": "関連エンティティ",
            "选择图节点": "グラフノードを選択",
            "严重等级": "深刻度",
            "名称": "名称",
            "描述": "説明",
            "生态": "エコシステム",
            "影响范围": "影響範囲",
            "来源链接": "参考リンク",
            "关联编号": "関連 ID",
            "弱点类型": "弱点タイプ",
            "发布时间": "公開日時",
            "更新时间": "更新日時",
            "修复方式": "修正方法",
            "别名": "別名",
            "影响组件": "影響コンポーネント",
            "查询结果": "照会ログ",
            "仅保存和展示 API 查询日志，不保存漏洞明细数据": "API 照会ログのみ保存・表示し、脆弱性詳細データは保存しません。",
            "刷新": "更新",
            "%d 条日志": "%d 件のログ",
            "搜索查询内容、状态或执行节点": "照会内容、状態、実行ノードを検索",
            "查询内容": "照会内容",
            "状态": "状態",
            "返回数": "戻り数",
            "图谱": "グラフ",
            "时间": "時刻",
            "暂无查询日志": "照会ログはありません",
            "通过知识图谱或智能问答触发漏洞查询后，这里只记录查询日志。": "ナレッジグラフまたは AI チャットで脆弱性照会を実行すると、ここには照会ログのみ記録されます。",
            "完成": "完了",
            "警告": "警告",
            "失败": "失敗",
            "运行中": "実行中",
            "节点": "ノード",
            "%d 个执行节点 · 后端固定情报接口": "%d 個の実行ノード · バックエンド固定インテリジェンス API",
            "查询日志详情": "照会ログ詳細",
            "查询摘要": "照会概要",
            "查询状态": "照会状態",
            "执行时间": "実行時間",
            "数据策略": "データ方針",
            "仅保留查询日志，不保存漏洞明细": "照会ログのみ保持し、脆弱性詳細は保存しません",
            "统计概览": "統計概要",
            "返回 %d 条 · 图谱 %d 节点 / %d 关系 · 本地写入 %d": "%d 件返却 · グラフ %d ノード / %d エッジ · ローカル書き込み %d",
            "图谱概览": "グラフ概要",
            "暂无图谱节点": "グラフノードはありません",
            "图谱节点": "グラフノード",
            "图谱关系": "グラフ関係",
            "执行日志": "実行ログ",
            "暂无执行日志": "実行ログはありません",
            "%@ · 共 %d 个执行节点": "%@ · %d 個の実行ノード",
            "%d 个节点": "%d 個のノード",
            "%@ · %@ / %d 条关系": "%@ · %@ / %d 件の関係",
            "返回记录": "返却レコード",
            "本地写入": "ローカル書き込み",
            "暂无执行记录": "実行記録はありません",
            "关闭": "閉じる",
            "识别问题意图": "意図を分類",
            "加载长期记忆": "長期記憶を読み込み",
            "检索漏洞知识": "脆弱性知識を検索",
            "实时补充记录": "リアルタイム記録を補完",
            "查询漏洞接口": "脆弱性 API を照会",
            "静态代码路径分析": "静的コードパス分析",
            "生成知识图谱": "ナレッジグラフ生成",
            "调用安全模型": "セキュリティモデル呼び出し",
            "生成回答": "回答生成",
            "生成分析报告": "分析レポート生成",
            "报告中心": "レポート",
            "上传项目清单与代码后，系统会分别展示依赖漏洞，以及 AST/CFG/DFG 路径中的具体漏洞位置和修复代码。": "プロジェクトマニフェストとコードをアップロードすると、依存関係脆弱性と AST/CFG/DFG パス上の具体的な位置、修正コードを分けて表示します。",
            "删除选中的 %d 份报告？": "選択した %d 件のレポートを削除しますか？",
            "取消": "キャンセル",
            "删除": "削除",
            "报告文件和对应记录会被永久删除，此操作无法撤销。": "レポートファイルと対応レコードは完全に削除されます。この操作は元に戻せません。",
            "分析报告": "分析レポート",
            "取消全选": "全選択解除",
            "全选": "全選択",
            "删除选中的报告": "選択したレポートを削除",
            "选择": "選択",
            "暂无分析报告": "分析レポートはありません",
            "下载报告": "レポートをダウンロード",
            "下载 Markdown": "Markdown をダウンロード",
            "下载 HTML": "HTML をダウンロード",
            "下载 PDF": "PDF をダウンロード",
            "报告 Markdown 已复制": "レポート Markdown をコピーしました",
            "复制 Markdown": "Markdown をコピー",
            "依赖漏洞 %d": "依存関係脆弱性 %d",
            "代码漏洞 %d": "コード脆弱性 %d",
            "请选择报告": "レポートを選択してください",
            "下载分析报告": "分析レポートをダウンロード",
            "下载%@分析报告": "%@ 分析レポートをダウンロード",
            "点击查看详细内容": "クリックして詳細を表示",
            "报告概览": "レポート概要",
            "%d 项": "%d 件",
            "代码": "コード",
            "复制代码": "コードをコピー",
            "报告已保存到 %@": "レポートを %@ に保存しました",
            "已删除 %d 份报告": "%d 件のレポートを削除しました",
            "API 返回 %d 条漏洞记录": "API が %d 件の脆弱性レコードを返しました",
            "欢迎回来": "おかえりなさい",
            "AI 驱动的安全知识库智能体\n漏洞分析 · 威胁情报 · 知识图谱": "AI 駆動のセキュリティ知識ベースエージェント\n脆弱性分析 · 脅威インテリジェンス · ナレッジグラフ",
            "创建您的安全智脑账户\n开启智能安全分析之旅": "SecFlow アカウントを作成\nインテリジェントなセキュリティ分析を開始",
            "智能问答，秒级响应安全咨询": "AI チャットがセキュリティ相談に秒単位で応答",
            "实时漏洞查询，多源接口关联": "リアルタイム脆弱性照会と複数 API の関連付け",
            "知识图谱关联漏洞与组件": "ナレッジグラフで脆弱性とコンポーネントを関連付け",
            "填写基本信息": "基本情報を入力",
            "验证邮箱地址": "メールアドレスを確認",
            "设置安全偏好": "セキュリティ設定を行う",
            "登录您的安全智脑账户": "SecFlow アカウントにサインイン",
            "邮箱地址": "メールアドレス",
            "请输入邮箱地址": "メールアドレスを入力",
            "密码": "パスワード",
            "请输入密码": "パスワードを入力",
            "登 录": "サインイン",
            "或": "または",
            "使用本机账户进入": "この Mac のアカウントで続行",
            "还没有账户？": "アカウントをお持ちでないですか？",
            "立即注册": "今すぐ登録",
            "创建账户": "アカウント作成",
            "加入安全智脑，提升安全分析效率": "SecFlow に参加してセキュリティ分析効率を高める",
            "姓": "姓",
            "名": "名",
            "请输入": "入力してください",
            "工作邮箱": "勤務先メール",
            "设置密码": "パスワード設定",
            "至少8位，包含字母和数字": "8 文字以上、英字と数字を含む",
            "确认密码": "パスワード確認",
            "请再次输入密码": "もう一度パスワードを入力",
            "所属组织（选填）": "所属組織（任意）",
            "公司或团队名称": "会社またはチーム名",
            "角色": "ロール",
            "安全分析师": "セキュリティアナリスト",
            "安全工程师": "セキュリティエンジニア",
            "安全管理员": "セキュリティ管理者",
            "其他": "その他",
            "我同意服务条款和隐私政策": "利用規約とプライバシーポリシーに同意します",
            "首次配置": "初回設定",
            "密钥仅加密保存在这台 Mac": "キーはこの Mac にのみ暗号化保存されます",
            "选择模型厂商": "プロバイダーを選択",
            "选择模型": "モデルを選択",
            "自定义模型 ID…": "カスタムモデル ID…",
            "填写连接信息": "接続情報を入力",
            "验证并完成": "検証して完了",
            "配置 AI 模型": "AI モデル設定",
            "完成连接后即可使用智能问答和报告分析": "接続完了後、AI チャットとレポート分析を利用できます",
            "第 %d / 4 步": "ステップ %d / 4",
            "请选择你已经开通 API 服务的厂商": "API サービスを有効化済みのプロバイダーを選択してください",
            "选择具体模型": "具体的なモデルを選択",
            "模型列表遵循 %@ 的接口规范": "モデル一覧は %@ の API 仕様に従います",
            "模型": "モデル",
            "输入厂商模型 ID": "プロバイダーのモデル ID を入力",
            "API Key 初始为空，需要使用者自行填写": "API Key は初期状態で空です。利用者が入力する必要があります",
            "API 地址": "API エンドポイント",
            "前往 %@ 获取 API Key": "%@ で API Key を取得",
            "验证连接": "接続を検証",
            "测试成功后才会把配置写入本机加密存储": "テスト成功後にのみ設定をローカル暗号化ストレージへ書き込みます",
            "厂商": "プロバイダー",
            "已填写，不显示明文": "入力済み、平文は表示しません",
            "正在测试": "テスト中",
            "正在保存": "保存中",
            "下一步": "次へ",
            "上一步": "戻る",
            "保存并进入": "保存して入る",
        ],
        .ko: [
            "安全提醒": "보안 알림",
            "暂无新的安全提醒": "새 보안 알림 없음",
            "漏洞总数": "전체 취약점",
            "严重漏洞": "심각 취약점",
            "高危漏洞": "고위험 취약점",
            "中危漏洞": "중위험 취약점",
            "低危漏洞": "저위험 취약점",
            "按漏洞编号聚合去重": "취약점 ID 기준 중복 제거",
            "等待首次批计算": "첫 배치 업데이트 대기",
            "最近更新：%@": "최근 업데이트: %@",
            "累计漏洞风险态势，后台持续增量更新": "누적 취약점 위험 현황, 백그라운드에서 지속 업데이트",
            "%@ 至 %@ 发布的漏洞风险态势": "%@부터 %@까지 공개된 취약점 위험 현황",
            "本地全量目录已就绪，共 %d 条": "로컬 전체 카탈로그 준비 완료, 총 %d건",
            "正在构建本地全量目录 %d%%": "로컬 전체 카탈로그 구축 중 %d%%",
            "正在准备本地全量目录": "로컬 전체 카탈로그 준비 중",
            "占全部漏洞 0%": "전체 취약점의 0%",
            "占全部漏洞 %d%%": "전체 취약점의 %d%%",
            "全部时间": "전체 기간",
            "最近 7 天": "최근 7일",
            "最近 30 天": "최근 30일",
            "最近 90 天": "최근 90일",
            "今年": "올해",
            "自定义范围": "사용자 지정 범위",
            "最新漏洞动态": "최신 취약점 동향",
            "最近一次批计算返回的漏洞记录": "최근 배치 업데이트에서 반환된 취약점 기록",
            "查看查询日志": "조회 로그 보기",
            "暂无漏洞数据": "취약점 데이터 없음",
            "批计算完成后将在这里显示最新漏洞。": "배치 업데이트 완료 후 최신 취약점이 여기에 표시됩니다.",
            "未提供漏洞标题": "취약점 제목 없음",
            "发布于 %@": "%@ 공개",
            "风险快速统计": "위험 빠른 통계",
            "漏洞情报风险图表": "취약점 인텔리전스 위험 차트",
            "按严重等级展示环形图与柱状图": "심각도별 링 차트와 막대 차트",
            "风险柱状图": "위험 막대 차트",
            "按漏洞数量排序": "취약점 수 기준 정렬",
            "数据来自本地批计算快照，并随时间范围筛选实时更新": "데이터는 로컬 배치 스냅샷에서 가져오며 선택한 시간 범위에 맞춰 업데이트됩니다",
            "严重": "심각",
            "高危": "높음",
            "中危": "중간",
            "低危": "낮음",
            "重点风险": "중점 위험",
            "暂无需要优先关注的漏洞": "우선 처리할 취약점 없음",
            "时间未知": "시간 알 수 없음",
            "未知": "알 수 없음",
            "安全总览已更新累计数据": "개요 누적 데이터 업데이트됨",
            "安全总览已按时间范围更新": "선택 기간으로 개요 업데이트됨",
            "安全总览已切换到所选发布日期范围": "개요가 선택한 공개일 범위로 전환됨",
            "本机数据服务已连接": "로컬 데이터 서비스 연결됨",
            "服务地址无效，请在设置中填写完整的 http 或 https 地址。": "서비스 주소가 올바르지 않습니다. 설정에서 완전한 http 또는 https URL을 입력하세요.",
            "服务返回了无法识别的响应。": "서비스가 인식할 수 없는 응답을 반환했습니다.",
            "本地数据解析失败：%@": "로컬 데이터 파싱 실패: %@",
            "应用内本地服务缺失，请重新安装 SecFlow。": "앱 내 로컬 서비스가 없습니다. SecFlow를 다시 설치하세요.",
            "本地服务启动失败：%@": "로컬 서비스 시작 실패: %@",
            "开发服务 %@ 无法连接。": "개발 서비스 %@에 연결할 수 없습니다.",
            "进程已退出，请查看 %@。": "프로세스가 종료되었습니다. %@을 확인하세요.",
            "等待本地服务就绪超时，请查看 %@。": "로컬 서비스 준비 대기 시간이 초과되었습니다. %@을 확인하세요.",
            "模型配置已启用。": "모델 설정이 활성화되었습니다.",
            "模型配置已保存，尚未启用。": "모델 설정이 저장되었지만 아직 활성화되지 않았습니다.",
            "未配置可用模型。": "사용 가능한 모델이 설정되지 않았습니다.",
            "模型接口返回格式不符合 OpenAI Chat Completions。": "모델 API 응답 형식이 OpenAI Chat Completions와 일치하지 않습니다.",
            "当前模型未返回可用结果。": "현재 모델이 사용 가능한 결과를 반환하지 않았습니다.",
            "模型接口调用成功。": "모델 API 호출에 성공했습니다.",
            "填入 API Key 后，可从厂商模型接口同步真实模型列表。": "API Key를 입력하면 공급자 API에서 실제 모델 목록을 동기화할 수 있습니다.",
            "API 地址需要包含 http:// 或 https://，当前显示内置推荐模型。": "API 주소에는 http:// 또는 https://가 포함되어야 합니다. 현재는 내장 추천 모델을 표시합니다.",
            "厂商接口未返回可用模型，已使用内置推荐模型。": "공급자 API가 사용 가능한 모델을 반환하지 않아 내장 추천 모델을 사용합니다.",
            "已从厂商模型接口同步模型列表。": "공급자 API에서 모델 목록을 동기화했습니다.",
            "固定接口可访问。": "고정 API에 접근할 수 있습니다.",
            "查询完成": "조회 완료",
            "查询失败": "조회 실패",
            "部分完成": "부분 완료",
            "等待查询": "조회 대기",
            "模型接口请求失败：%@": "모델 API 요청 실패: %@",
            "厂商模型列表同步失败，已使用内置推荐模型：%@": "공급자 모델 목록 동기화에 실패하여 내장 추천 모델을 사용합니다: %@",
            "%@ 的接口地址需要包含 http:// 或 https://。": "%@ 엔드포인트에는 http:// 또는 https://가 포함되어야 합니다.",
            "大模型配置已保存并启用": "AI 모델 설정 저장 및 활성화됨",
            "大模型连接已断开": "AI 모델 연결 해제됨",
            "连接测试已完成": "연결 테스트 완료",
            "个人资料": "프로필",
            "管理头像、联系方式和岗位资料，资料仅保存在本机。": "아바타, 연락처, 직무 정보를 관리합니다. 데이터는 이 Mac에만 저장됩니다.",
            "保存资料": "프로필 저장",
            "上传头像": "아바타 업로드",
            "移除": "제거",
            "支持 JPG、PNG、WebP，文件大小不超过 2MB": "JPG, PNG, WebP 지원, 최대 2 MB",
            "姓名": "이름",
            "工号": "사번",
            "所属部门": "부서",
            "职位": "직책",
            "邮箱": "이메일",
            "手机号": "휴대폰",
            "个人简介": "소개",
            "%d / 200 字": "%d / 200자",
            "姓名不能为空": "이름은 비워둘 수 없습니다",
            "邮箱不能为空": "이메일은 비워둘 수 없습니다",
            "个人资料已保存": "프로필 저장됨",
            "头像上传失败：%@": "아바타 업로드 실패: %@",
            "头像已上传并保存在本机": "아바타가 업로드되어 로컬에 저장되었습니다",
            "头像已移除": "아바타 제거됨",
            "仅支持 JPG、PNG 或 WebP 图片": "JPG, PNG 또는 WebP 이미지만 지원합니다",
            "头像文件不能超过 2MB": "아바타 파일은 2 MB를 초과할 수 없습니다",
            "无法读取图片内容": "이미지 내용을 읽을 수 없습니다",
            "请选择一个有效的图片文件": "유효한 이미지 파일을 선택하세요",
            "智能问答": "AI 문답",
            "新对话": "새 대화",
            "新建对话": "새 대화 시작",
            "添加项目清单、代码附件或完整项目目录": "프로젝트 매니페스트, 코드 첨부 또는 전체 프로젝트 폴더 추가",
            "输入安全问题，获取智能分析…": "보안 질문을 입력해 AI 분석 받기…",
            "停止生成": "중지",
            "发送": "전송",
            "松开即可添加项目或附件": "놓으면 프로젝트 또는 첨부가 추가됩니다",
            "支持拖入 Python、Go、C/C++、Rust、Solidity、Java 项目；会自动忽略构建产物目录": "Python, Go, C/C++, Rust, Solidity, Java 프로젝트를 드롭할 수 있습니다. 빌드 산출물 폴더는 자동 무시됩니다.",
            "请输入包含文字或数字的具体安全问题": "문자 또는 숫자가 포함된 구체적인 보안 질문을 입력하세요",
            "本地安全分析暂时不可用。": "로컬 보안 분석을 일시적으로 사용할 수 없습니다.",
            "附件读取失败：%@": "첨부 읽기 실패: %@",
            "请拖入项目清单或代码文件": "프로젝트 매니페스트 또는 코드 파일을 드롭하세요",
            "无法识别拖入的文件": "드롭한 파일을 식별할 수 없습니다",
            "最多支持添加 %d 个项目文件": "최대 %d개 프로젝트 파일을 추가할 수 있습니다",
            "项目文件内容过大，已超过本次分析的上传上限": "프로젝트 파일이 너무 커서 이번 분석 업로드 한도를 초과했습니다",
            "未找到可分析的项目清单或代码文件": "분석 가능한 프로젝트 매니페스트 또는 코드 파일을 찾지 못했습니다",
            "请分析附件 %@": "첨부 %@ 분석",
            "请分析 %d 个附件：%@": "%d개 첨부 분석: %@",
            "移除附件": "첨부 제거",
            "漏洞": "취약점",
            "%@ 漏洞分析报告": "%@ 취약점 분석 보고서",
            "漏洞描述": "취약점 설명",
            "风险待核验": "위험 확인 대기",
            "根据知识图谱分析，您的系统中以下组件可能受到影响：": "지식 그래프 분석 기준, 다음 컴포넌트가 영향을 받을 수 있습니다:",
            "组件版本范围": "컴포넌트 버전 범위",
            "涉及版本": "영향 버전",
            "修复版本": "수정 버전",
            "修复方案": "수정 방법",
            "缓释措施": "완화 조치",
            "参考链接": "참고 링크",
            "代码片段": "코드 조각",
            "修复代码片段": "수정 코드 조각",
            "受影响版本待核验": "영향 버전 확인 대기",
            "影响 %@": "%@ 영향",
            "有帮助": "도움됨",
            "需改进": "개선 필요",
            "已复制": "복사됨",
            "复制": "복사",
            "分享": "공유",
            "正在分析 · %d 秒": "분석 중 · %d초",
            "模型处理中 · %d 秒": "모델 처리 중 · %d초",
            "已停止生成": "생성 중지됨",
            "依赖关系图表": "의존성 관계 차트",
            "依赖桑基图": "의존성 Sankey",
            "构建文件 / 代码文件 → 依赖 → CVE → 修复版本": "빌드 파일 / 코드 파일 → 의존성 → CVE → 수정 버전",
            "风险等级环形图": "심각도 링 차트",
            "按严重等级统计漏洞数量": "심각도별 취약점 수",
            "依赖风险柱状图": "의존성 위험 막대 차트",
            "命中漏洞最多的依赖": "취약점이 가장 많이 매칭된 의존성",
            "依赖影响有向无环图": "의존성 영향 DAG",
            "按层级展示依赖、漏洞与修复路径": "의존성, 취약점, 수정 경로를 계층으로 표시",
            "命中": "매칭",
            "知识图谱": "지식 그래프",
            "输入 CVE 编号，生成漏洞知识图谱": "CVE ID를 입력해 취약점 지식 그래프 생성",
            "查询图谱": "그래프 조회",
            "暂无图谱": "그래프 없음",
            "拖动画布移动 · 双指捏合或按钮缩放": "드래그로 이동 · 핀치 또는 버튼으로 확대/축소",
            "缩小": "축소",
            "放大": "확대",
            "居中": "가운데",
            "组件": "컴포넌트",
            "弱点": "약점",
            "修复": "수정",
            "公告": "권고",
            "关联公告": "관련 권고",
            "暂无更多详情": "추가 상세 없음",
            "关联实体": "관련 엔티티",
            "选择图节点": "그래프 노드 선택",
            "严重等级": "심각도",
            "名称": "이름",
            "描述": "설명",
            "生态": "생태계",
            "影响范围": "영향 범위",
            "来源链接": "참고 링크",
            "关联编号": "관련 ID",
            "弱点类型": "약점 유형",
            "发布时间": "공개 시간",
            "更新时间": "업데이트 시간",
            "修复方式": "수정 방법",
            "别名": "별칭",
            "影响组件": "영향 컴포넌트",
            "查询结果": "조회 로그",
            "仅保存和展示 API 查询日志，不保存漏洞明细数据": "API 조회 로그만 저장 및 표시하고 취약점 상세 데이터는 저장하지 않습니다.",
            "刷新": "새로고침",
            "%d 条日志": "%d개 로그",
            "搜索查询内容、状态或执行节点": "조회 내용, 상태 또는 실행 노드 검색",
            "查询内容": "조회 내용",
            "状态": "상태",
            "返回数": "반환 수",
            "图谱": "그래프",
            "时间": "시간",
            "暂无查询日志": "조회 로그 없음",
            "通过知识图谱或智能问答触发漏洞查询后，这里只记录查询日志。": "지식 그래프 또는 AI 문답에서 취약점 조회를 실행하면 여기에 조회 로그만 기록됩니다.",
            "完成": "완료",
            "警告": "경고",
            "失败": "실패",
            "运行中": "실행 중",
            "节点": "노드",
            "%d 个执行节点 · 后端固定情报接口": "%d개 실행 노드 · 백엔드 고정 인텔리전스 API",
            "查询日志详情": "조회 로그 상세",
            "查询摘要": "조회 요약",
            "查询状态": "조회 상태",
            "执行时间": "실행 시간",
            "数据策略": "데이터 정책",
            "仅保留查询日志，不保存漏洞明细": "조회 로그만 보관하고 취약점 상세는 저장하지 않음",
            "统计概览": "통계 개요",
            "返回 %d 条 · 图谱 %d 节点 / %d 关系 · 本地写入 %d": "%d건 반환 · 그래프 %d 노드 / %d 관계 · 로컬 쓰기 %d",
            "图谱概览": "그래프 개요",
            "暂无图谱节点": "그래프 노드 없음",
            "图谱节点": "그래프 노드",
            "图谱关系": "그래프 관계",
            "执行日志": "실행 로그",
            "暂无执行日志": "실행 로그 없음",
            "%@ · 共 %d 个执行节点": "%@ · 실행 노드 %d개",
            "%d 个节点": "%d개 노드",
            "%@ · %@ / %d 条关系": "%@ · %@ / %d개 관계",
            "返回记录": "반환 기록",
            "本地写入": "로컬 쓰기",
            "暂无执行记录": "실행 기록 없음",
            "关闭": "닫기",
            "识别问题意图": "의도 분류",
            "加载长期记忆": "장기 기억 로드",
            "检索漏洞知识": "취약점 지식 검색",
            "实时补充记录": "실시간 기록 보강",
            "查询漏洞接口": "취약점 API 조회",
            "静态代码路径分析": "정적 코드 경로 분석",
            "生成知识图谱": "지식 그래프 생성",
            "调用安全模型": "보안 모델 호출",
            "生成回答": "답변 생성",
            "生成分析报告": "분석 보고서 생성",
            "报告中心": "보고서",
            "上传项目清单与代码后，系统会分别展示依赖漏洞，以及 AST/CFG/DFG 路径中的具体漏洞位置和修复代码。": "프로젝트 매니페스트와 코드를 업로드하면 의존성 취약점과 AST/CFG/DFG 경로의 정확한 위치, 수정 코드를 분리해 표시합니다.",
            "删除选中的 %d 份报告？": "선택한 보고서 %d개를 삭제할까요?",
            "取消": "취소",
            "删除": "삭제",
            "报告文件和对应记录会被永久删除，此操作无法撤销。": "보고서 파일과 해당 기록이 영구 삭제됩니다. 이 작업은 취소할 수 없습니다.",
            "分析报告": "분석 보고서",
            "取消全选": "전체 선택 해제",
            "全选": "전체 선택",
            "删除选中的报告": "선택한 보고서 삭제",
            "选择": "선택",
            "暂无分析报告": "분석 보고서 없음",
            "下载报告": "보고서 다운로드",
            "下载 Markdown": "Markdown 다운로드",
            "下载 HTML": "HTML 다운로드",
            "下载 PDF": "PDF 다운로드",
            "报告 Markdown 已复制": "보고서 Markdown 복사됨",
            "复制 Markdown": "Markdown 복사",
            "依赖漏洞 %d": "의존성 취약점 %d",
            "代码漏洞 %d": "코드 취약점 %d",
            "请选择报告": "보고서를 선택하세요",
            "下载分析报告": "분석 보고서 다운로드",
            "下载%@分析报告": "%@ 분석 보고서 다운로드",
            "点击查看详细内容": "클릭하여 상세 보기",
            "报告概览": "보고서 개요",
            "%d 项": "%d개 항목",
            "代码": "코드",
            "复制代码": "코드 복사",
            "报告已保存到 %@": "보고서를 %@에 저장했습니다",
            "已删除 %d 份报告": "보고서 %d개 삭제됨",
            "API 返回 %d 条漏洞记录": "API가 취약점 기록 %d건 반환",
            "欢迎回来": "다시 오신 것을 환영합니다",
            "AI 驱动的安全知识库智能体\n漏洞分析 · 威胁情报 · 知识图谱": "AI 기반 보안 지식 베이스 에이전트\n취약점 분석 · 위협 인텔리전스 · 지식 그래프",
            "创建您的安全智脑账户\n开启智能安全分析之旅": "SecFlow 계정 만들기\n지능형 보안 분석 시작",
            "智能问答，秒级响应安全咨询": "AI 문답으로 보안 상담에 초 단위 응답",
            "实时漏洞查询，多源接口关联": "실시간 취약점 조회 및 다중 API 연계",
            "知识图谱关联漏洞与组件": "지식 그래프로 취약점과 컴포넌트 연결",
            "填写基本信息": "기본 정보 입력",
            "验证邮箱地址": "이메일 주소 확인",
            "设置安全偏好": "보안 선호 설정",
            "登录您的安全智脑账户": "SecFlow 계정에 로그인",
            "邮箱地址": "이메일 주소",
            "请输入邮箱地址": "이메일 주소 입력",
            "密码": "비밀번호",
            "请输入密码": "비밀번호 입력",
            "登 录": "로그인",
            "或": "또는",
            "使用本机账户进入": "이 Mac 계정으로 계속",
            "还没有账户？": "아직 계정이 없나요?",
            "立即注册": "지금 등록",
            "创建账户": "계정 만들기",
            "加入安全智脑，提升安全分析效率": "SecFlow에 참여해 보안 분석 효율을 높이세요",
            "姓": "성",
            "名": "이름",
            "请输入": "입력하세요",
            "工作邮箱": "업무 이메일",
            "设置密码": "비밀번호 설정",
            "至少8位，包含字母和数字": "8자 이상, 문자와 숫자 포함",
            "确认密码": "비밀번호 확인",
            "请再次输入密码": "비밀번호를 다시 입력",
            "所属组织（选填）": "소속 조직(선택)",
            "公司或团队名称": "회사 또는 팀 이름",
            "角色": "역할",
            "安全分析师": "보안 분석가",
            "安全工程师": "보안 엔지니어",
            "安全管理员": "보안 관리자",
            "其他": "기타",
            "我同意服务条款和隐私政策": "서비스 약관 및 개인정보 처리방침에 동의합니다",
            "首次配置": "첫 설정",
            "密钥仅加密保存在这台 Mac": "키는 이 Mac에만 암호화 저장됩니다",
            "选择模型厂商": "공급자 선택",
            "选择模型": "모델 선택",
            "自定义模型 ID…": "사용자 지정 모델 ID…",
            "填写连接信息": "연결 정보 입력",
            "验证并完成": "검증 후 완료",
            "配置 AI 模型": "AI 모델 설정",
            "完成连接后即可使用智能问答和报告分析": "연결이 완료되면 AI 문답과 보고서 분석을 사용할 수 있습니다",
            "第 %d / 4 步": "%d / 4 단계",
            "请选择你已经开通 API 服务的厂商": "API 서비스를 활성화한 공급자를 선택하세요",
            "选择具体模型": "구체 모델 선택",
            "模型列表遵循 %@ 的接口规范": "모델 목록은 %@ API 규격을 따릅니다",
            "模型": "모델",
            "输入厂商模型 ID": "공급자 모델 ID 입력",
            "API Key 初始为空，需要使用者自行填写": "API Key는 초기값이 비어 있으며 사용자가 직접 입력해야 합니다",
            "API 地址": "API 엔드포인트",
            "前往 %@ 获取 API Key": "%@에서 API Key 받기",
            "验证连接": "연결 검증",
            "测试成功后才会把配置写入本机加密存储": "테스트 성공 후에만 설정을 로컬 암호화 저장소에 기록합니다",
            "厂商": "공급자",
            "已填写，不显示明文": "입력됨, 평문 표시 안 함",
            "正在测试": "테스트 중",
            "正在保存": "저장 중",
            "下一步": "다음",
            "上一步": "이전",
            "保存并进入": "저장 후 들어가기",
        ],
    ]

    static let table: [AppLanguage: [L10nKey: String]] = [
        .zhHans: [
            .appName: "安全智脑",
            .appVersion: "v1.2.0",
            .navOverview: "总览",
            .navAssistant: "智能问答",
            .navKnowledgeGraph: "知识图谱",
            .navQueryResults: "查询结果",
            .navInformation: "信息咨询",
            .navReports: "报告中心",
            .settings: "设置",
            .settingsSubtitle: "配置 AI 模型以启用智能问答",
            .languageTitle: "语言与区域",
            .languageSubtitle: "选择客户端界面语言，设置会保存在这台 Mac。",
            .interfaceLanguage: "界面语言",
            .languageHint: "切换后导航、设置、功能界面和智能体回答会按所选语言展示；代码、包名、版本号和链接保持原文。",
            .llmAccess: "AI 模型接入",
            .llmAccessSubtitle: "先选择模型厂商，再选择具体模型，最后填入 API 地址和 Key。",
            .selectProvider: "1. 选择厂商",
            .selectModel: "2. 选择模型",
            .customModel: "自定义模型 ID…",
            .customModelPlaceholder: "输入厂商文档中的模型 ID，例如 gpt-5.6 或 claude-sonnet-4-5",
            .syncModels: "同步模型",
            .syncing: "同步中",
            .apiAndKey: "3. 填写 API 和 Key",
            .apiKeyLocalOnly: "你的密钥仅存储在本地，不会上传",
            .apiEndpoint: "API 地址",
            .apiKey: "API Key",
            .showApiKey: "显示 API Key",
            .hideApiKey: "隐藏 API Key",
            .howToGetApiKey: "如何获取 API Key?",
            .testing: "测试中",
            .testConnection: "测试连接",
            .saving: "保存中",
            .saveAndEnable: "保存并启用",
            .connected: "已连接",
            .disconnected: "未连接",
            .disconnect: "断开",
            .savedModel: "已保存模型",
            .localConfig: "来自本地配置",
            .providerModelsSynced: "已从 %@ 模型接口同步 %d 个模型。",
            .builtinModelsShown: "当前显示内置推荐模型。",
            .defaultModelHint: "默认显示推荐模型；填入 Key 后可同步厂商模型列表，也可选择自定义模型 ID。",
            .justNow: "刚刚",
            .lastVerifiedAt: "%@ · 上次验证于 %@",
            .chooseModelAndKey: "请选择模型并保存 API Key",
            .refreshData: "刷新数据",
            .signOut: "退出到登录页",
            .localServiceStarting: "本地服务启动中",
            .localDataConnected: "本机数据已连接",
            .setupChecking: "正在检查本机配置",
            .setupCheckingSubtitle: "正在确认 AI 模型是否已完成配置",
            .setupFailed: "无法读取本机配置",
            .retry: "重试",
            .dateRangeHelp: "选择发布日期范围",
            .previousMonth: "上个月",
            .nextMonth: "下个月",
            .selectMonth: "选择月份",
            .selectYear: "选择年份",
        ],
        .en: [
            .appName: "SecFlow AI",
            .appVersion: "v1.2.0",
            .navOverview: "Overview",
            .navAssistant: "Assistant",
            .navKnowledgeGraph: "Knowledge Graph",
            .navQueryResults: "Query Logs",
            .navInformation: "Information",
            .navReports: "Reports",
            .settings: "Settings",
            .settingsSubtitle: "Configure an AI model to enable chat and reports",
            .languageTitle: "Language & Region",
            .languageSubtitle: "Choose the client language. The setting is stored on this Mac.",
            .interfaceLanguage: "Interface language",
            .languageHint: "Navigation, settings, feature pages, and assistant responses follow the selected language. Code, package names, versions, and links stay unchanged.",
            .llmAccess: "AI model connection",
            .llmAccessSubtitle: "Choose a provider, select a model, then enter the API endpoint and key.",
            .selectProvider: "1. Provider",
            .selectModel: "2. Model",
            .customModel: "Custom model ID…",
            .customModelPlaceholder: "Enter a model ID from the provider docs, e.g. gpt-5.6 or claude-sonnet-4-5",
            .syncModels: "Sync models",
            .syncing: "Syncing",
            .apiAndKey: "3. API and key",
            .apiKeyLocalOnly: "Your key is stored locally and never uploaded.",
            .apiEndpoint: "API endpoint",
            .apiKey: "API Key",
            .showApiKey: "Show API Key",
            .hideApiKey: "Hide API Key",
            .howToGetApiKey: "How do I get an API Key?",
            .testing: "Testing",
            .testConnection: "Test connection",
            .saving: "Saving",
            .saveAndEnable: "Save and enable",
            .connected: "Connected",
            .disconnected: "Not connected",
            .disconnect: "Disconnect",
            .savedModel: "Saved model",
            .localConfig: "From local configuration",
            .providerModelsSynced: "Synced models from %@: %d.",
            .builtinModelsShown: "Showing built-in recommended models.",
            .defaultModelHint: "Recommended models are shown by default. Enter a key to sync provider models or use a custom model ID.",
            .justNow: "just now",
            .lastVerifiedAt: "%@ · verified %@",
            .chooseModelAndKey: "Choose a model and save an API Key",
            .refreshData: "Refresh data",
            .signOut: "Back to login",
            .localServiceStarting: "Local service starting",
            .localDataConnected: "Local data connected",
            .setupChecking: "Checking local configuration",
            .setupCheckingSubtitle: "Confirming whether the AI model is configured",
            .setupFailed: "Cannot read local configuration",
            .retry: "Retry",
            .dateRangeHelp: "Choose publication date range",
            .previousMonth: "Previous month",
            .nextMonth: "Next month",
            .selectMonth: "Select month",
            .selectYear: "Select year",
        ],
        .ja: [
            .appName: "SecFlow AI",
            .navOverview: "概要",
            .navAssistant: "AI チャット",
            .navKnowledgeGraph: "ナレッジグラフ",
            .navQueryResults: "照会ログ",
            .navInformation: "セキュリティ情報",
            .navReports: "レポート",
            .settings: "設定",
            .settingsSubtitle: "AI モデルを設定してチャットとレポートを有効化します",
            .languageTitle: "言語と地域",
            .languageSubtitle: "クライアントの表示言語を選択します。この設定はこの Mac に保存されます。",
            .interfaceLanguage: "表示言語",
            .languageHint: "ナビゲーション、設定、機能画面、AI 回答は選択した言語で表示されます。コード、パッケージ名、バージョン、リンクは原文のままです。",
            .llmAccess: "AI モデル接続",
            .llmAccessSubtitle: "プロバイダー、モデル、API エンドポイントと Key の順に設定します。",
            .selectProvider: "1. プロバイダー",
            .selectModel: "2. モデル",
            .customModel: "カスタムモデル ID…",
            .customModelPlaceholder: "プロバイダー文書のモデル ID を入力します。例: gpt-5.6、claude-sonnet-4-5",
            .syncModels: "モデル同期",
            .syncing: "同期中",
            .apiAndKey: "3. API と Key",
            .apiKeyLocalOnly: "Key はこの端末にのみ保存され、アップロードされません。",
            .apiEndpoint: "API エンドポイント",
            .apiKey: "API Key",
            .showApiKey: "API Key を表示",
            .hideApiKey: "API Key を隠す",
            .howToGetApiKey: "API Key の取得方法",
            .testing: "テスト中",
            .testConnection: "接続テスト",
            .saving: "保存中",
            .saveAndEnable: "保存して有効化",
            .connected: "接続済み",
            .disconnected: "未接続",
            .disconnect: "切断",
            .savedModel: "保存済みモデル",
            .localConfig: "ローカル設定から",
            .providerModelsSynced: "%@ から %d 個のモデルを同期しました。",
            .builtinModelsShown: "内蔵の推奨モデルを表示しています。",
            .defaultModelHint: "既定では推奨モデルを表示します。Key を入力するとプロバイダーモデルを同期できます。",
            .justNow: "たった今",
            .lastVerifiedAt: "%@ · 最終確認 %@",
            .chooseModelAndKey: "モデルを選択し API Key を保存してください",
            .refreshData: "データ更新",
            .signOut: "ログインへ戻る",
            .localServiceStarting: "ローカルサービス起動中",
            .localDataConnected: "ローカルデータ接続済み",
            .setupChecking: "ローカル設定を確認中",
            .setupCheckingSubtitle: "AI モデル設定を確認しています",
            .setupFailed: "ローカル設定を読み取れません",
            .retry: "再試行",
            .dateRangeHelp: "公開日の範囲を選択",
            .previousMonth: "前月",
            .nextMonth: "翌月",
            .selectMonth: "月を選択",
            .selectYear: "年を選択",
        ],
        .ko: [
            .appName: "SecFlow AI",
            .navOverview: "개요",
            .navAssistant: "AI 문답",
            .navKnowledgeGraph: "지식 그래프",
            .navQueryResults: "조회 로그",
            .navInformation: "보안 정보",
            .navReports: "보고서",
            .settings: "설정",
            .settingsSubtitle: "AI 모델을 설정해 문답과 보고서를 활성화합니다",
            .languageTitle: "언어 및 지역",
            .languageSubtitle: "클라이언트 표시 언어를 선택합니다. 설정은 이 Mac에 저장됩니다.",
            .interfaceLanguage: "표시 언어",
            .languageHint: "탐색, 설정, 기능 화면, AI 답변은 선택한 언어로 표시됩니다. 코드, 패키지명, 버전, 링크는 원문을 유지합니다.",
            .llmAccess: "AI 모델 연결",
            .llmAccessSubtitle: "공급자와 모델을 선택한 뒤 API 주소와 Key를 입력하세요.",
            .selectProvider: "1. 공급자",
            .selectModel: "2. 모델",
            .customModel: "사용자 지정 모델 ID…",
            .customModelPlaceholder: "공급자 문서의 모델 ID를 입력하세요. 예: gpt-5.6 또는 claude-sonnet-4-5",
            .syncModels: "모델 동기화",
            .syncing: "동기화 중",
            .apiAndKey: "3. API 및 Key",
            .apiKeyLocalOnly: "Key는 로컬에만 저장되며 업로드되지 않습니다.",
            .apiEndpoint: "API 주소",
            .apiKey: "API Key",
            .showApiKey: "API Key 표시",
            .hideApiKey: "API Key 숨기기",
            .howToGetApiKey: "API Key는 어떻게 받나요?",
            .testing: "테스트 중",
            .testConnection: "연결 테스트",
            .saving: "저장 중",
            .saveAndEnable: "저장 후 사용",
            .connected: "연결됨",
            .disconnected: "연결 안 됨",
            .disconnect: "연결 해제",
            .savedModel: "저장된 모델",
            .localConfig: "로컬 설정에서 가져옴",
            .providerModelsSynced: "%@에서 모델 %d개를 동기화했습니다.",
            .builtinModelsShown: "내장 추천 모델을 표시합니다.",
            .defaultModelHint: "기본으로 추천 모델을 표시합니다. Key를 입력하면 공급자 모델을 동기화할 수 있습니다.",
            .justNow: "방금",
            .lastVerifiedAt: "%@ · 마지막 검증 %@",
            .chooseModelAndKey: "모델을 선택하고 API Key를 저장하세요",
            .refreshData: "데이터 새로고침",
            .signOut: "로그인으로 돌아가기",
            .localServiceStarting: "로컬 서비스 시작 중",
            .localDataConnected: "로컬 데이터 연결됨",
            .setupChecking: "로컬 설정 확인 중",
            .setupCheckingSubtitle: "AI 모델 설정 여부를 확인합니다",
            .setupFailed: "로컬 설정을 읽을 수 없습니다",
            .retry: "다시 시도",
            .dateRangeHelp: "게시일 범위 선택",
            .previousMonth: "이전 달",
            .nextMonth: "다음 달",
            .selectMonth: "월 선택",
            .selectYear: "연도 선택",
        ],
    ]
}
